# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ftest"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Marie"]
  s.date = "2013-09-24"
  s.description = "Simple and flexible ruby fuzz testing DSL"
  s.email = "pingu@anchor.net.au"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "README.rdoc",
    "Rakefile",
    "lib/ftest.rb",
    "lib/ftest/assertion_dsl.rb",
    "lib/ftest/binary_dsl.rb",
    "lib/ftest/formatting.rb",
    "lib/ftest/ftest.rb",
    "lib/ftest/fuzz_dsl.rb",
    "lib/ftest/runner.rb",
    "lib/ftest/runner_dsl.rb",
    "lib/ftest/scenario.rb",
    "lib/ftest/scenario_dsl.rb",
    "spec/assertion_dsl_spec.rb",
    "spec/binary_dsl_spec.rb",
    "spec/ftest_spec.rb",
    "spec/fuzz_dsl_spec.rb",
    "spec/runner_dsl_spec.rb",
    "spec/runner_spec.rb",
    "spec/scenario_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/test"
  ]
  s.homepage = "http://github.com/christian-marie/ftest"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby fuzz testing"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

